export const PAGE_LOADED = "PAGE_LOADED"

export const SEARCH_RESULTS_RECEIVED = "SEARCH_RESULTS_RECEIVED"

export const SEARCH_TERMS_CHANGED = "SEARCH_TERMS_CHANGED"

export const SEARCH_RESULTS_REQUESTED = "SEARCH_RESULTS_REQUESTED"

export const PAGED_FORWARD = "PAGED_FORWARD"

export const PAGED_BACKWARD = "PAGED_BACKWARD"

export const ALL_CLEARED = "ALL_CLEARED"

export const SORT_ORDER_CHANGED = "SORT_ORDER_CHANGED"